version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      # This port only needs to be exposed for local development.
      # In production, the web container is behind a reverse proxy (Caddy).
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data
  caddy:
    image: caddy:2-alpine
    command: /bin/sh -c "caddy reverse-proxy --from ${HOSTNAME} --to web:3000"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    env_file:
      - .env
    environment:
      HOSTNAME: "${HOSTNAME}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pg_data:
  redis_data:
  caddy_data:
  caddy_config: