version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=decisiveteam
      - POSTGRES_PASSWORD=decisiveteam
      - POSTGRES_DB=decisive_team_development

volumes:
  pg_data:
