version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - HOSTNAME=localhost:3000
      - REDIS_URL=redis://redis:6379/0
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - HOSTNAME=localhost:3000
      - REDIS_URL=redis://redis:6379/0
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=decisiveteam
      - POSTGRES_PASSWORD=decisiveteam
      - POSTGRES_DB=decisive_team_development
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
