---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/teams":
    get:
      summary: list teams
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
